source 'https://cdn.cocoapods.org/'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ReactSample' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'GoogleAds-IMA-iOS-SDK', '3.13.0'
  pod 'NativoSDK', '~> 6.0.0'

  target 'ReactSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
